### ISSUE TITLE
add journals

### ISSUE THREAD

**Issue by RafaelAPB** [jianyu-niu/blockchain_conference_paper#16]
Are journals (e.g., ACM CSUR, IEEE Transactions on Computers) also being considered on this list?

**Comment by gitferry** [comment]
@RafaelAPB Good idea! I just updated README and added the table of listed journals along with an example from TKDE. Please bring the journal papers in following that example (e.g., you may need to add the reference for the new journal into the table of listed journals). Many thanks!
