### ISSUE TITLE
Seems that "EVMFuzz: Differential Fuzz Testing of Ethereum Virtual Machine" is not published in OSDI'21

### ISSUE THREAD

**Issue by IceCY** [jianyu-niu/blockchain_conference_paper#19]

**Comment by IceCY** [comment]
Instead, it is published in "ESEC/FSE 2019" with name "EVMFuzzer: detect EVM vulnerabilities via fuzz testing
"

**Comment by gitferry** [comment]
@IceCY Nice catch. It is "Finding Consensus Bugs in Ethereum via Multi-transaction Differential Fuzzing" that is accepted to OSDI'21.
